spring.application.name=Ticketo

# db connection
spring.datasource.url=jdbc:postgresql://localhost:5432/ticketo
spring.datasource.username=postgres
spring.datasource.password=123456789


# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# keycloak
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/realms/ticketo